name: Standalone on Windows

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - "**/*.md"
      - ".github/workflows/standalone.yml"
      - ".github/workflows/ci-build.yml"

  pull_request:
    paths-ignore:
      - "**/*.md"
      - ".github/workflows/standalone.yml"
      - ".github/workflows/ci-build.yml"

jobs:
  build_windows:
    name: Windows
    runs-on: windows-2022
    strategy:
      matrix:
        rust: [1.71]
    env:
      WASMEDGE_DIR: ${{ github.workspace }}\WasmEdge
      WASMEDGE_BUILD_DIR: ${{ github.workspace }}\WasmEdge\build
      WASMEDGE_PLUGIN_PATH: ${{ github.workspace }}\WasmEdge\build\wasmedge\plugins\wasmedge_process
      LD_LIBRARY_PATH: ${{ github.workspace }}\WasmEdge\build\lib\api
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependency
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install cmake ninja vswhere

      - name: Set up Windows 10 SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        with:
          sdk-version: 19041

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install winget
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install WasmEdge
        run: winget install wasmedge --disable-interactivity --accept-source-agreements

      - name: Run in the standalone mode
        run: |
          # $env:Path="$env:Path;C:\Program Files\WasmEdge\lib"
          cargo test -p wasmedge-sdk --all --features aot,ffi,standalone -- --nocapture --test-threads=1
